#
# KapEasyMenu Plugin
# by kap35
# https://kap35.gitbook.io/kap-easy-menu-plugin/
#
# This plugin is licensed under the GNU General Public License v3.0
# https://www.gnu.org/licenses/gpl-3.0.en.html
#



