name: KapEasyMenu
main: fr.kap35.kapeasymenu.KapEasyMenu
version: 2.0.2
author: kap35
website: https://kap35.gitbook.io/kap-easy-menu-plugin/
description: A plugin to create menus easily
api-version: 1.19

commands:
  menuExists:
    description: Check if a menu exists
    usage: /menuExists <menuName>
    permission: kapeasymenu.menuExists
    permission-message: You don't have the permission to use this command
  menuList:
    description: List all menus
    usage: /menuList
    permission: kapeasymenu.menuList
    permission-message: You don't have the permission to use this command
  openMenu:
    description: Open a menu
    usage: /openMenu <menuName>
    permission: kapeasymenu.openMenu
    permission-message: You don't have the permission to use this command
  setmenuactive:
    description: Set a menu active or inactive
    usage: /setmenuactive <menuName> <true|false>
    permission: kapeasymenu.setmenuactive
    permission-message: You don't have the permission to use this command
